name: "bmp280"
version: "1.0.0"
slug: "bmp280"
description: "Addon to read bmp280 sensor data and post to Home Assistant"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: manual
devices:
  - "/dev/i2c-1:/dev/i2c-1:rwm"
options:
  api_base_url:
    description: "Base URL of Home Assistant API"
    type: string
    required: true
    example: "http://192.168.137.253:8123/api/states"
  api_token:
    description: "Long-Lived Access Token for Home Assistant API"
    type: string
    required: true
    example: "your_long_lived_access_token"
schema:
  api_base_url: str
  api_token: str

