name: env_api
version: dev
slug: env_api
description: "test_sp_api"
arch:
  - aarch64
  - amd64
  - armv7
map:
  - ssl
  - bmp180
  - bmp280
  - sht31
  - sht45
  - oxygen
options:
  addr-bmp: none
  addr-sht: none
  addr-oxy: none
  bmp180: false
  bmp280: false
  sht31: false
  sht45: false
  oxygen: false
schema:
  bmp180: bool
  bmp280: bool
  sht31: bool
  sht45: bool
  oxygen: bool
  addr-bmp: list(0x76|0x77)
  addr-sht: list(0x44|0x45)
  addr-oxy: list(0x70|0x71|0x72|0x73)
devices:
  - "/dev/i2c-5:rwm"
homeassistant_api: true
hassio_api: true
